# Paths
DATA_RAW_PATH = "data/raw/"
DATA_PROCESSED_PATH = "data/processed/"
DATA_AUGMENTED_PATH = "data/augmented/"
OUTPUT_MODELS_PATH = "outputs/models/"
OUTPUT_FIGURES_PATH = "outputs/figures/"
OUTPUT_RESULTS_PATH = "outputs/results/"

# View sizes
GLOBAL_VIEW_LENGTH = 2001
LOCAL_VIEW_LENGTH = 201
PHASE_WINDOW = 0.05

# Training
BATCH_SIZE = 64
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4
MAX_EPOCHS = 100
EARLY_STOPPING_PATIENCE = 10
N_FOLDS = 5
RANDOM_SEED = 42

# CNN Global
CNN_GLOBAL_FILTERS = [16, 32, 64, 128]
CNN_GLOBAL_KERNEL = 5
CNN_GLOBAL_POOL = 5

# CNN Local
CNN_LOCAL_FILTERS = [16, 32, 64]
CNN_LOCAL_KERNEL = 3
CNN_LOCAL_POOL = 3

# Transformer
TRANSFORMER_D_MODEL = 64
TRANSFORMER_NHEAD = 8
TRANSFORMER_LAYERS = 4
TRANSFORMER_DIM_FF = 256
TRANSFORMER_DROPOUT = 0.1

# Focal Loss
FOCAL_ALPHA = 0.25
FOCAL_GAMMA = 2.0

# Dropout
DROPOUT_RATE = 0.5
MC_DROPOUT_PASSES = 50

# Uncertainty thresholds
UNCERTAINTY_HIGH = 0.05
UNCERTAINTY_MEDIUM = 0.15

# Column names from Kepler dataset
LABEL_COLUMN = "koi_disposition"
PERIOD_COLUMN = "koi_period"
EPOCH_COLUMN = "koi_time0bk"
POSITIVE_LABEL = "CONFIRMED"
NEGATIVE_LABEL = "FALSE POSITIVE"
